travis:
  secure:
    BINSTAR_TOKEN: Hi8+C98aVP9qfm3LRQQgNWwNmclWEsMpKowp1TVO7ibtkta93RCmOTTKn7TTb9wk8ThMwHGrxXwTJXkiYQ0nNlzEXcRVkVv5eonn0sC/b5odWyjmU0r14slWPPRZDuZ+Kxc+sEne84jCs53FI2GfGSoTAIAWKQuTuwqtw1xZvG2f7QL3cwpvXn20lNCpbAlL//vcG2lq6j0SUQcj+SIneblg8fOmXBW7khY6rb1ey6MADHz0pL/8ktCYuIVJroLhD5vlBeGS2EGql0nL3FL9kVOk3duSAXgFtMf+J9vSmc+X3s1ajyl2DsQgVJgRJAdF5OgUrZ0OpPgYkfJPt7GZXbQBXQ9pWPmCz9ROn5wruiAXQthQ2b0fBIuyM1XtWFRRcVISG2r6UqcbwkrvwAECgPDDXObFq2kT6pzhi1zxcw4iPAv5fn3I0fCtdGduRXpP6bugKVexEBxKKaSWRfCOmaXuYM1ufoKF6QWBE1Av2BMyVB8dV7WTKq1P4HpnxO9W9RQDH+WDJ7E5O/NWQa/QNv0DkLplt31WfiCQrT43jArUvc+SpCvQI70NC7UV/HfP6g3+5lfWlEnlNMBdEE743HYFe2oJcR6971VVC+tgDzglA3Y/QZb6pMf8d9wEH9AUZyTbaoNdAdXeBN2QwITJJmwnz21oZSLep0vtcKTF20M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
